[input.columns]
depth   =   "Depth (m)"
qc      =   "qc (MPa)"
fs      =   "fs (kPa)"
u2      =   "u2 (kPa)"
u0      =   "u0 (kPa)"

[input.parameters]
a_ratio     =   0.80
gamma_w     =   9.81
gamma_s     =   18.7
p_ref       =   101.33
rolling     =   3

[output.columns]
sigv_tot    =   "σv_tot (kPa)"
sigv_eff    =   "σv_eff (kPa)"
qt          =   "qt (MPa)"
fr          =   "Fr (%)"
bq          =   "Bq (adim.)"
n           =   "n (adim.)"
qtn         =   "Qtn (adim.)"
ic          =   "Ic (adim.)"
convg       =   "convg (?)"
cd          =   "CD (adim.)"
ib          =   "IB (adim.)"

[output.parameters]
max_iter    =   999
tolerance   =   0.001
